### ISSUE TITLE
Transfer tokens missing in openChannel

### ISSUE THREAD

**Issue by LGBourrec** [crossbario/xbr-protocol#107] opened 2020-04-02 16:27 UTC
Reading smart contracts of the protocol, I don't see any token transfer in XBRChannel's openChannel function. The only ones transfers found occur when channels are closed.

**Comment by oberstet** [comment] 2020-04-02 17:00
yes, pls see https://github.com/crossbario/xbr-protocol/issues/104.

actually, this is a left-over from the recent big expansion/refactoring and the code posted in the issue comment needs to be added back (and adjusted)

closing this issue, as it is a duplicate of above

**Closed by oberstet** 2020-04-02 17:00 UTC
